### ISSUE TITLE
List of break exercises

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-user-stories#1]
## Value Proposition

**As a** user
**I need** a list of break exercises
**to be able to** get inspiration for active breaks. 

## Description

<img width="200" alt="wireframe1" src="https://user-images.githubusercontent.com/106118696/179205455-90b77a7c-ca8b-4b4b-9259-663d042d43f8.png">

## Acceptance Criteria

- [ ] Each break exercise is displayed in a different card.
- [ ] Every card contains a category headline, a short exercise description, the repeat cycle in minutes and the duration in seconds or minutes. 
- [ ] The list is scrollable.
- [ ] The page title „Pausen“ is displayed. 

## Tasks

(for developers team)

- [ ] Create global styles
- [ ] Create component (card)
- [ ] Add to Storybook
- [ ] Write test
- [ ] Create db.js with break exercises
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hi Magda,

really nice first user story, I have nothing to comment 🎉
