### ISSUE TITLE
Filter break exercises by category

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-user-stories#2]
## Value Proposition

**As a** user
**I need** to filter all break exercises by category
**to be able to** have a better overview of the exercises that interest me at the moment.

## Description

<img width="400" alt="wireframe2" src="https://user-images.githubusercontent.com/106118696/179239093-f58a6afe-490d-441d-a686-a29b9ea7e1ff.png">

## Acceptance Criteria

- [ ] A category section is displayed right above the list of cards.
- [ ] The category section contains the headline „Kategorie“, one tag component per category and one tag representing all categories.
- [ ] Screen 1: The „all“ tag is selected by default and all cards from all categories are displayed underneath.
- [ ] The selected tag has a different styling than the not selected tags.
- [ ] Screen 2: Only one tag can be selected at a time and only the cards corresponding to the selected category will be displayed.
- [ ] The category section and the list is scrollable.

## Tasks

(for developers team)

- [ ] Create components (categories, tag)
- [ ] Add styling
- [ ] Add to Storybook
- [ ] Write tests
- [ ] Add to App

**Comment by yvonneadam** [comment]
I really like how detailed you describe the user story, no questions left unanswered for me 
(a new feature branch in tasks could be added)
