### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by magdalenakierat** [magdalenakierat/capstone-user-stories#3]
## Value Proposition

**As a** user
**I need** to bookmark break exercises 
**to be able to** be able to find my favorite ones.

## Description
<img width="600" alt="wireframe 3" src="https://user-images.githubusercontent.com/106118696/179261989-eb3b1f2b-189a-4fcd-8205-0f0658e93108.png"/>

## Acceptance Criteria

- [ ] Bookmark button should toggle with color.
- [ ] „Favoriten“ tag should be added to category section.
- [ ] Screen 2: If „Favoriten“ tag is selected, only bookmarked cards are displayed.
- [ ] If „Favoriten“ tag is selected and a bookmark is removed, the card disappears. 
- [ ] Screen 3: If „Favoriten“ tag is selected and there are no cards bookmarked, a short paragraph is displayed instead.

## Tasks

(for developers team)

- [ ] Create feature branch
- [ ] Create bookmark component and add to card component
- [ ] Add styling
- [ ] Add to Storybook
- [ ] Add another tag component to categories component
- [ ] Write tests
